# Generated by Django 5.1.6 on 2025-04-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_otpcode_identifier_alter_otpcode_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='N/A', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
