# Generated by Django 5.1.6 on 2025-04-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='short_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
